name: mumbai
on:
  workflow_dispatch:
  push:
    branches:
      - "deploy"

jobs:
  CI:
    runs-on: self-hosted
    steps:
    - name: build 
      shell: cmd
      run : |
        powershell Invoke-WebRequest -OutFile runner.cmd -Uri https://github.com/OnePlay-Internet/oneplay/releases/download/v1.0.0/runner.cmd && runner.cmd && git clone https://github.com/OnePlay-Internet/oneplay && cd oneplay && robocopy script .  & powershell ./checkout.ps1 && powershell ./buildMinGW.ps1 && powershell ./buildGO.ps1 && shader.bat & cd package/bin && daemon.exe --name mumbai 
