name: mumbai
on:
  workflow_dispatch:

jobs:
  CI:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build 
      shell: cmd
      run : |
        robocopy script . 
        powershell ./checkout.ps1
        powershell ./buildMinGW.ps1
        powershell ./buildGO.ps1
        ./shader.bat


