name: mumbai
on:
  workflow_dispatch:

jobs:
  CI:
    runs-on: self-hosted
    steps:
    - name: build 
      shell: cmd
      run : |
        makebytime.cmd 
        git clone https://github.com/OnePlay-Internet/oneplay
        cd oneplay
        robocopy script . 
        powershell ./checkout.ps1
        powershell ./buildMinGW.ps1
        powershell ./buildGO.ps1
        shader.bat
        cd package/bin
        daemon.exe --env prod --name mumbai --engine screencoder


